version: 2
updates:
  - package-ecosystem: npm
    directory: 'frontend/'
    schedule:
      interval: monthly
    assignees:
      - aleksanderbl29
    groups:
      all-deps:
        patterns:
          - '*'
